import {nextui} from '@nextui-org/theme'

/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}'
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#00eefc",
        "surface-variant": "#24252d",
        "on-tertiary-fixed": "#1f0052",
        "on-primary": "#005d63",
        "on-secondary-fixed-variant": "#8300b4",
        "secondary-fixed-dim": "#eaaeff",
        "prism-background": "#0d0e13",
        "outline-variant": "#47474e",
        "outline": "#75757b",
        "surface": "#0d0e13",
        "on-tertiary": "#290067",
        "on-tertiary-fixed-variant": "#4700a7",
        "secondary-dim": "#b90afc",
        "tertiary-fixed": "#bda1ff",
        "surface-container-low": "#121319",
        "surface-container-high": "#1e1f26",
        "surface-container-lowest": "#000000",
        "tertiary-dim": "#874cff",
        "surface-dim": "#0d0e13",
        "primary-dim": "#00deec",
        "on-error": "#490006",
        "inverse-on-surface": "#54545b",
        "secondary-fixed": "#f0c1ff",
        "on-error-container": "#ffa8a3",
        "on-primary-fixed": "#003f43",
        "on-surface-variant": "#abaab1",
        "error-dim": "#d7383b",
        "on-prism-background": "#f7f5fd",
        "on-tertiary-container": "#f8f1ff",
        "on-secondary-fixed": "#58007a",
        "surface-tint": "#8ff5ff",
        "primary-container": "#00eefc",
        "surface-container-highest": "#24252d",
        "on-primary-fixed-variant": "#005e64",
        "secondary": "#d575ff",
        "on-secondary-container": "#fff5fc",
        "on-primary-container": "#005359",
        "tertiary": "#ac89ff",
        "on-surface": "#f7f5fd",
        "secondary-container": "#9800d0",
        "surface-bright": "#2a2c34",
        "on-secondary": "#390050",
        "inverse-primary": "#006a71",
        "primary-fixed-dim": "#00deec",
        "primary": "#8ff5ff",
        "error-container": "#9f0519",
        "surface-container": "#181920",
        "tertiary-fixed-dim": "#b190ff",
        "tertiary-container": "#7000ff",
        "inverse-surface": "#faf8ff",
        "error": "#ff716c",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)"],
        body: ["var(--font-space-grotesk)"],
        label: ["var(--font-space-grotesk)"],
        sans: ["var(--font-space-grotesk)"],
      },
    },
  },
  darkMode: "class",
  plugins: [nextui()],
  // plugins: [nextui(), require("@tailwindcss/typography")],
}

export default config;
